### ISSUE TITLE
☂️ Add support for Typo3 11.5.x

### ISSUE THREAD

**Issue by tlueder** [PHORAX/formhandler#89]
Filing as an umbrella bug for the overall feature of adding all fixes for Typo3 11.5.x

Split up the work done in RP #83 

### System setup:
php 7.4
Typo3 v11.5.x
debug mode on
error level 12290

### Work log
- [ ] dev and updated dependencies #86 
- [ ] persistence configuration #87 
- [ ] fix TCA Utility #88 
- [ ] adding types (up to php 7.4 support)
- [ ] set strict_types = 1 in all files
- [ ] adding null checks
- [ ] removed dead code

### New features
- [ ] fix resolvePath starting with typo3conf
- [ ] handle multiple template files

**Comment by tlueder** [comment]
@pulponair are you still interested in moving this forward?
The first 3 PRs are important for the next steps and I would like to base my work on them. 

I would like to bring all of our bug fixes to this public repro. But if no one else need this, we will just keep using our internal version.

**Comment by SvenJuergens** [comment]
@tlueder would be nice to have all bugfixes online :)

**Comment by tlueder** [comment]
I would like that too. But even my RP https://github.com/PHORAX/formhandler/pull/83 is now so many commits behind our internal git. That at some point I don't see the benefit of going backward to this anymore.

We use this plugin in our projects and have fixed or rewrote all parts that we are using. like ajax validators 
Or another point is to cleanup the code base to activate phpstan in a meaningful way.

But we don't have the resources to fix everything at once, so we do it once we use a new part and then fix whatever comes up.

So this has to be a step by step process or we just dump a big PR and say "deal with it".

In the end, I don't care either way. But having no response is a problem.

**Comment by SvenJuergens** [comment]
hi @tlueder 
you are absolutely right, it is a bit frustrating when there is no feedback at all and no response to pull requests. I also had some pull requests here that I deleted at some point, because no feedback came or at some point were no longer up to date because of other pull requests. 

@pulponair @7elix do you still have interest to continue the project? Would it be possible for you to refer to selected forks in the start page readme? or to give others write access to this repository? or what do you think about it? I know this is always a time and budget issue as well. It's just a pity that when the will of others is already there to support and help, that then unfortunately no feedback comes.

**Comment by 7elix** [comment]
Good evening @tlueder ,

thank you for your pull requests. 

We use formhandler with TYPO3 based on this repository and fix bugs as they come up. We are open to pull requests. 

I do not see the need for this umbrella issue any more since the overall compatibility is delivered. I will close this issue soon. 

Therefore continue to send single issues with single pull requests, please. Theses can be reviewed and applied in acceptable time. Much appreciated! ❤️

Concerning your overall strategy I am sadly not of any help. I can not help with your overall strategy since I can not rate the status of your internal development. If I were in the position to migrate and publish internal code I would publish the whole repository as a fork to give everyone the opportunity to create something better.

**Comment by tlueder** [comment]
Define single issue please.

Making this plugin compatible with Typo3 V11 would be a single issue. 
And I could remove the new features from my first PR so that it contains only the fixes.

But it would still be a big one.

I didn't ask for help with my overall strategy. I only mentioned it to illustrate my point.
The reason, I would like bring our fixes to this repro is to have a bigger user base and hopefully more eyes on it than just my team. 

But since it took you more than month to say. "Oh no, please file small bite sized issues with nice small PRs." And to be honest, you not even said that. I guess there's just not enough interest. 

Thanks.

**Comment by 7elix** [comment]
Sure, no problem. Let me explain "single issue" by exmaple:
The single issues are created now and linked the pull requests accordingly. 
This way disjunct issues with handy merge requests can easily be reviewed and merged.

### Created milestoness instead of umbrella issue
- https://github.com/PHORAX/formhandler/milestone/1

### Created individual issues for bugs and errors
- https://github.com/PHORAX/formhandler/issues/90
- https://github.com/PHORAX/formhandler/issues/91
- https://github.com/PHORAX/formhandler/issues/92

### Created individual issues for enhancements
- https://github.com/PHORAX/formhandler/issues/93
- https://github.com/PHORAX/formhandler/issues/94
- https://github.com/PHORAX/formhandler/issues/95

**Comment by tlueder** [comment]
Do what ever you like with the code I provided. 
I already have a fully working version of this plugin and don't want to wast anymore time on this.
